name: Publish

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add gradle portal token
      run: |
        cat << EOS > /github/home/gradle.properties
        gradle.publish.key=$GRADLE_PUBLISH_KEY
        gradle.publish.secret=$GRADLE_PUBLISH_SECRET
        EOS
    - name: Set tag version
      run: echo ::set-env name=TAG_VERSION::${GITHUB_REF#refs/tags/}
    - name: Publish this plugin to gradle portal
      run: ./gradlew clean publishPlugins
